version: "3"

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
       - pg_data:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=good_place
  backend:
    build: .
    command: bash -c "cd good_place && 
          poetry install && 
          poetry run aerich init -t db.utils.TORTOISE_CONFIG &&
          poetry run aerich init-db &&
          poetry run aerich upgrade &&
          poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    depends_on:
      - db

volumes:
  pg_data:
